---
# Role tasks

- block:
    - name: install operating system packages
      package:
        name: "{{ package.keys() | first }}"
        state: "{{ package.values() | first }}"
      loop: >-
        {{ lookup('template', 'packages.yml.j2') | from_yaml
           + (packages_python is not none)
              | ternary([{'python-pip': 'present'},
                         {'python-setuptools': 'present'} ], []) }}
      loop_control:
        loop_var: package
        label: "{{ package.keys() | first }}"
      vars:
        packages_spec: "{{ packages_os }}"
      tags:
        - role::packages
        - role::packages::os

    - name: install python packages
      pip:
        name: "{{ package.keys() | first }}"
        state: "{{ package.values() | first }}"
        extra_args: "{{ packages_pip_extra_args }}"
      loop: >-
        {{ lookup('template', 'packages.yml.j2') | from_yaml }}
      loop_control:
        loop_var: package
        label: "{{ package.keys() | first }}"
      vars:
        packages_spec: "{{ packages_python }}"
      tags:
        - role::packages
        - role::packages::python
  environment: "{{ proxy_client_environment }}"
  tags:
    - role::packages
