---
# Role tasks

# - include_tasks: os.yml
#   when: >-
#     packages_os.keys() | list | length > 0
#     or packages_python.keys() | list | length > 0
#     or packages_os_load_from_hostvars | bool
#   tags:
#     - role::packages
#     - role::packages::os

- include_tasks: venv.yml
  when:
    - packages_python.keys() | list | length > 0
    - packages_python_virtualenv is defined
    - packages_python_virtualenv | length > 0
  tags:
    - role::packages
    - role::packages::python

- include_tasks: facts.yml
  when:
    - packages_python.keys() | list | length > 0
    - packages_python_virtualenv is defined
    - packages_python_virtualenv | length > 0
    - packages_python_set_ansible_interpreter | bool
  tags:
    - role::packages

- include_tasks: python.yml
  when: >-
    packages_python.keys() | list | length > 0
    or packages_python_load_from_hostvars | bool
  tags:
    - role::packages
    - role::packages::python
