---

- name: Setup packages
  block:
    - name: Gather facts
      ansible.builtin.include_tasks: facts.yml

    - name: Setup prerequisites
      ansible.builtin.include_tasks: prerequisites.yml

    - name: Setup operating system packages
      ansible.builtin.include_tasks: packages_os.yml
      when: packages_os_process_required
      tags:
        - role::packages::os

    - name: Setup operating system packages
      ansible.builtin.include_tasks: packages_python.yml
      when: packages_python_process_required
      tags:
        - role::packages::python
  tags:
    - role::packages
