---
# Role tasks

- block:
    - name: install operating system packages
      package:
        name: "{{ package.name }}"
        state: "{{ package.state }}"
      loop: >-
        {{ lookup('template', 'packages.yml.j2') | from_yaml
           + (packages_python is not none)
              | ternary([{ 'name': 'python-pip', 'state': 'present'},
                         { 'name': 'python-setuptools', 'state': 'present'} ],
                        []) }}
      loop_control:
        loop_var: package
        label: "{{ package.name }}"
      vars:
        packages_spec: "{{ packages_os }}"
      tags:
        - role::packages
        - role::packages::os

    - name: install python packages
      pip:
        name: "{{ package.name }}"
        state: "{{ package.state }}"
        extra_args: >-
          {{ packages_pip_extra_args }}
          {{ package.pip_extra_args | default('') }}
      loop: >-
        {{ lookup('template', 'packages.yml.j2') | from_yaml }}
      loop_control:
        loop_var: package
        label: "{{ package.name }}"
      vars:
        packages_spec: "{{ packages_python }}"
      tags:
        - role::packages
        - role::packages::python
  environment: "{{ proxy_client_environment }}"
  tags:
    - role::packages
