---
# Role tasks

- block:
    - name: Gather facts
      include_tasks: facts.yml

    - name: Setup operating system packages
      include_tasks: packages_os.yml
      when: packages_os_process_required
      tags:
        - role::packages::os

    - name: Setup operating system packages
      include_tasks: packages_python.yml
      when: packages_python_process_required
      tags:
        - role::packages::python
  tags:
    - role::packages
