---
# Role tasks

- block:
    - include_tasks: packages_os.yml
      when: packages_os_process_required
      tags:
          - role::packages::os

    - include_tasks: packages_python.yml
      tags:
        - role::packages::python
      when: packages_python_process_required
  tags:
    - role::packages
