---
# Role tasks

- include_tasks: os.yml
  when: packages_os is not none or packages_python is not none
  tags:
    - role::packages
    - role::packages::os

- include_tasks: venv.yml
  when:
    - packages_python is not none
    - packages_python_virtualenv is defined
    - packages_python_virtualenv | length > 0
  tags:
    - always

- include_tasks: facts.yml
  when:
    - packages_python is not none
    - packages_python_virtualenv is defined
    - packages_python_virtualenv | length > 0
    - packages_python_set_ansible_interpreter
  tags:
    - always

- include_tasks: python.yml
  when: packages_python is not none
  tags:
    - role::packages
    - role::packages::python
