---
# Setup operating system packages tasks

- block:
    - name: Get operating system packages facts
      package_facts:


    - block:
        - name: Gather capabilities present
          shell: rpm -qa --provides | cut -d = -f 1
          args:
            warn: no
          changed_when: no
          register: packages_provides_result

        - name: Setup fact with capabilites present
          set_fact:
            packages_capabilities_present: >-
              {{ packages_provides_result.stdout_lines
                 | map("trim")
                 | list }}
      when: packages_capabilities_present is undefined

    - block:
        - name: Gather packages groups present
          command: yum --cacheonly groups list
          args:
            warn: no
          changed_when: no
          register: packages_groups_result
          environment:
            LANGUAGE: en_US
            LANG: en_US

        - name: Setup fact with packages groups present
          set_fact:
            packages_groups_present: >-
              {{ lookup("template", "groups.yml.j2") | from_yaml }}

      when: packages_groups_present is undefined

    - include_role:
        name: amtega.epel
      when: packages_python.keys() | list | length > 0

    - name: Setup operating system packages
      package:
        name: "{{ package.name }}"
        state: "{{ package.state }}"
      loop: "{{ packages_to_manage }}"
      loop_control:
        loop_var: package
        label: >-
          {{ package.name | default('') }} {{ package.state | default('') }}

    - name: Setup fact with operating packages managed
      set_fact:
        packages_os_managed: >-
          {{ packages_os_managed | default([]) + packages_to_manage }}
      when: packages_to_manage | length > 0

  environment: "{{ proxy_client_environment | default({}) }}"
  vars:
    pip_package: >-
      {{ lookup("template", "pip_package.j2") | trim }}

    python_setup_tools_package: python-setuptools

    python_virtualenv_package: >-
      {{ lookup("template", "virtualenv_package.j2") | trim }}

    python_pip_packages_spec:
      - name: "{{ pip_package }}"
        state: present

    python_setup_tools_packages_spec:
      - name: "{{ python_setup_tools_package }}"
        state: present

    python_virtualenv_packages_spec:
      - name: "{{ python_virtualenv_package }}"
        state: present

    python_extra_packages: >-
      {{ (pip_package not in ansible_facts.packages.keys() | list)
         | ternary(python_pip_packages_spec, [])
         + (python_setup_tools_package
            not in ansible_facts.packages.keys() | list)
           | ternary(python_setup_tools_packages_spec, [])
         + (python_virtualenv_package
            not in ansible_facts.packages.keys() | list)
           | ternary(python_virtualenv_packages_spec, []) }}

    python_extra_packages_spec:
      all:
        all: "{{ python_extra_packages }}"

    packages_to_manage: >-
      {{ lookup('template', 'packages.yml.j2') | from_yaml }}

    packages_already_managed: "{{ packages_os_managed | default([]) }}"

    packages_already_present: >-
      {{ ansible_facts.packages.keys() | list
         + packages_capabilities_present
         + packages_groups_present }}

    packages_spec: "{{ packages_os }}"

    packages_spec_hostvars: "{{ packages_os_hostvars | default([]) }}"
  tags:
    - role::packages
    - role::packages::os
