---
# Setup python packages tasks

- block:
    - name: Setup python
      include_tasks: python.yml
      when:
        - ansible_facts.distribution | lower in ["centos", "redhat"]
        - ansible_facts.distribution_major_version is version("7", "<")

    - name: Determine python packages to be managed and setup virtualenv
      _packages:
        family: python
      register: packages_python_process_result

    - name: Setup python packages
      pip:
        name: "{{ package.name }}"
        state: "{{ package.state }}"
        virtualenv: >-
          {{ package.virtualenv
             | default(packages_python_virtualenv)
             | default(omit) }}
        virtualenv_command: >-
          {{ package.virtualenv_command
             | default(packages_python_virtualenv_command)
             | default("virtualenv") }}
        virtualenv_python: >-
          {{ package.virtualenv_python
             | default(packages_python_virtualenv_python)
             | default(omit) }}
        virtualenv_site_packages: >-
          {{ package.virtualenv_site_packages
             | default(packages_python_virtualenv_site_packages)
             | default(omit) }}
        extra_args: >-
          {{ package.extra_args
             | default(packages_python_extra_args)
             | default(omit) }}
      register: packages_python_setup_result
      loop: "{{ packages_python_process_result.packages }}"
      loop_control:
        loop_var: package
        label: "{{ package.name }} {{ package.state }}"
      notify: "{{ packages_python_notify }}"
      environment:
        LANGUAGE: en_US.utf8
        LANG: en_US.utf8
        LC_ALL: en_US.utf8
      vars:
        ansible_python_interpreter: >-
          {{ packages_python_process_result.python_interpreter }}

    - name: Setup ansible python interpreter
      set_fact:
        ansible_python_interpreter: >-
          {{ packages_python_process_result.python_interpreter }}
      when: packages_python_set_ansible_interpreter | bool

    - name: Setup fact with python packages setup result
      set_fact:
        packages_python_result: >-
          {{ packages_python_setup_result | default({}) }}
      when: packages_python_process_result.packages | length > 0

  environment: >-
    {{ proxy_client_environment
       | default({})
       | combine(packages_tmp_dir_environment) }}
  tags:
    - role::packages::python
