---
- name: Setup operating system packages with yum
  ansible.builtin.yum:
    disable_plugin: "{{ packages_disable_plugin_value }}"
    disable_gpg_check: >-
      {{ package.disable_gpg_check
         | default(packages_disable_gpg_check)
         | default(omit) }}
    enable_plugin: "{{ packages_enable_plugin_value }}"
    name: "{{ package.name }}"
    state: "{{ package.state }}"
  register: packages_os_setup_result
  loop: "{{ packages_os_process_result.packages }}"
  loop_control:
    loop_var: package
    label: >-
      {{ package.name | default('') }} {{ package.state | default('') }}
  notify: "{{ packages_os_notify }}"
  environment: "{{ packages_environment }}"
  tags:
    - role::packages
    - role::packages::os
    - role::packages::os::yum
