---
# Setup operating system packages with dnf tasks

- name: Setup operating system packages
  dnf:
    disable_plugin: "{{ packages_disable_plugin_value }}"
    enable_plugin: "{{ packages_enable_plugin_value }}"
    name: "{{ package.name }}"
    state: "{{ package.state }}"
  register: packages_os_setup_result
  loop: "{{ packages_os_process_result.packages }}"
  loop_control:
    loop_var: package
    label: >-
      {{ package.name | default('') }} {{ package.state | default('') }}
  notify: "{{ packages_os_notify }}"
  environment: >-
    {{ proxy_client_environment
       | default({})
       | combine(packages_tmp_dir_environment) }}
  tags:
    - role::packages
    - role::packages::os
    - role::packages::os::dnf
