---
# Setup python packages tasks

- block:
    - include_tasks: virtualenv.yml
      when: packages_python_virtualenv | default("") | length > 0
      tags:
        - always

    - name: Determine python packages to be managed
      packages_to_manage:
        family: python
      register: packages_python_to_manage_result

    - name: Setup python packages
      pip:
        name: "{{ package.name }}"
        state: "{{ package.state }}"
        virtualenv: >-
          {{ package.virtualenv
             | default(packages_python_virtualenv)
             | default(omit) }}
        virtualenv_command: >-
          {{ package.virtualenv_command
             | default(packages_python_virtualenv_command)
             | default("virtualenv") }}
        virtualenv_python: >-
          {{ package.virtualenv_python
             | default(packages_python_virtualenv_python)
             | default(omit) }}
        virtualenv_site_packages: >-
          {{ package.virtualenv_site_packages
             | default(packages_python_virtualenv_site_packages)
             | default(omit) }}
        extra_args: >-
          {{ package.extra_args
             | default(packages_python_extra_args)
             | default(omit) }}
      register: packages_python_setup_result
      loop: "{{ packages_python_to_manage_result.packages }}"
      loop_control:
        loop_var: package
        label: "{{ package.name }} {{ package.state }}"
      notify: "{{ packages_python_notify }}"

    - name: Setup fact with python packages setup result
      set_fact:
        packages_python_result: >-
          {{ packages_python_setup_result | default({}) }}
      when: packages_python_to_manage_result.packages | length > 0

  environment: "{{ proxy_client_environment }}"
  tags:
    - role::packages::python
