---

- name: Setup operating system packages
  block:
    - name: Setup EPEL
      ansible.builtin.include_role:
        name: amtega.epel
      when:
        - ansible_facts.distribution_major_version is version("7", "==")
        - ansible_local.epel is undefined

    - name: Determine operating system packages to be managed
      _packages:
        family: os
      register: packages_os_process_result

    - ansible.builtin.include_tasks: >-
        packages_os_{{ packages_os_process_result.module }}.yml

    - name: Setup fact with operating packages setup result
      ansible.builtin.set_fact:
        packages_os_result: "{{ packages_os_setup_result | default({}) }}"
      when: packages_os_process_result.packages | length > 0
  environment: "{{ _packages_environment }}"
  tags:
    - role::packages
    - role::packages::os
