---
# Setup operating system packages tasks

- block:
    - name: Setup EPEL
      include_role:
        name: amtega.epel
      when: ansible_local.epel is undefined

    - name: Determine operating system packages to be managed
      _packages:
        family: os
      register: packages_os_process_result

    - include_tasks: "packages_os_{{ packages_os_process_result.module }}.yml"

    - name: Setup fact with operating packages setup result
      set_fact:
        packages_os_result: "{{ packages_os_setup_result | default({}) }}"
      when: packages_os_process_result.packages | length > 0

  environment: >-
    {{ proxy_client_environment
       | default({})
       | combine(packages_tmp_dir_environment) }}
  tags:
    - role::packages
    - role::packages::os
