---

- name: Setup operating system packages with yum
  ansible.builtin.yum:
    disable_plugin: "{{ _packages_disable_plugin_value | default(omit) }}"
    disable_gpg_check: >-
      {{ packages_package_item.disable_gpg_check
         | default(packages_disable_gpg_check)
         | default(omit) }}
    enable_plugin: "{{ _packages_enable_plugin_value | default(omit) }}"
    name: "{{ packages_package_item.name }}"
    state: "{{ packages_package_item.state }}"
  register: packages_os_setup_result
  loop: "{{ packages_os_process_result.packages }}"
  loop_control:
    loop_var: packages_package_item
    label: >-
      {{ packages_package_item.name | default("") }}
      {{ packages_package_item.state | default("") }}
  notify: "{{ packages_os_notify }}"
  environment: "{{ _packages_environment }}"
  tags:
    - role::packages
    - role::packages::os
    - role::packages::os::yum
