---

- name: Setup proxy client
  include_role:
    name: amtega.proxy_client
  vars:
    proxy_client_permanent: no

- name: Select operating system packages host variables
  include_role:
    name: amtega.select_hostvars
  when: packages_os_load_from_hostvars | bool
  vars:
    select_hostvars_query:
      pattern: "^packages_os_.*"
      exclude_pattern: >-
        {{ "^packages_os_("
           + "load_from_hostvars|"
           + "process_result|"
           + "setup_result|"
           + "result)$" }}
      fact_name: packages_os_hostvars
      output_type: list

- name: Select python packages host variables
  include_role:
    name: amtega.select_hostvars
  when: packages_python_load_from_hostvars | bool
  vars:
    select_hostvars_query:
      pattern: "^packages_python_.*"
      exclude_pattern: >-
        {{ "^packages_python_("
           + "load_from_hostvars|"
           + "virtualenv|"
           + "extra_args|"
           + "set_ansible_interpreter|"
           + "bin_dir|"
           + "process_result|"
           + "setup_result|"
           + "source_binary_check_result|"
           + "result).*$" }}
      fact_name: packages_python_hostvars
      output_type: list
