---
# Setup python packages tasks

- block:
    - name: Get python packages facts
      command: "{{ packages_python_bin_dir }}pip list"
      changed_when: no
      when: packages_python is not none
      register: packages_get_python_facts_result

    - name: Setup python packages
      pip:
        name: "{{ package.name }}"
        state: "{{ package.state }}"
        virtualenv: >-
          {{ package.virtualenv | default(omit) }}
        virtualenv_command: >-
          {{ package.virtualenv_command
             | default("virtualenv") }}
        virtualenv_python: >-
          {{ package.virtualenv_python
             | default(omit) }}
        virtualenv_site_packages: >-
          {{ package.virtualenv_site_packages
             | default(omit) }}
        extra_args: >-
          {{ package.extra_args
             | default(omit) }}
      loop: "{{ packages_to_manage }}"
      loop_control:
        loop_var: package
        label: "{{ package.name }} {{ package.state }}"

    - name: Setup fact with python packages managed
      set_fact:
        packages_python_managed: >-
          {{ packages_python_managed | default([]) + packages_to_manage }}
  environment: "{{ proxy_client_environment }}"
  vars:
    packages_to_manage: >-
      {{ lookup('template', 'packages.yml.j2') | from_yaml }}

    packages_already_managed: "{{ packages_python_managed | default([]) }}"

    packages_already_present: >-
      {{ packages_get_python_facts_result.stdout_lines
         | default([])
         | map("regex_replace", "(.*) \(.*\)", "\1")
         | list }}

    packages_spec: "{{ packages_python }}"

    packages_spec_hostvars: "{{ packages_python_hostvars | default([]) }}"
  tags:
    - role::packages
    - role::packages::python
