---
# Setup python

- name: Setup python
  block:
    - name: Check python binary
      ansible.builtin.stat:
        path: "{{ packages_python_source_binary }}"
      register: packages_python_source_binary_check_result

    - name: Compile python
      ansible.builtin.include_tasks: python_compile.yml
      when: not packages_python_source_binary_check_result.stat.exists
  tags:
    - role::packages
    - role::packages::os
    - role::packages::python
