---
# Role setup facts tasks

- block:
    - name: Setup python virtualenv
      command: >-
        /usr/bin/virtualenv \
        --python={{ ansible_python_interpreter }} \
        {{ (packages_python_virtualenv_site_packages)
           | ternary("--system-site-packages", "") }} \
        {{ packages_python_virtualenv }}
      args:
        creates: "{{ packages_python_virtualenv }}"
      vars:
        packages_python_bin_suffix: >-
          {{ (ansible_facts.python.version.major is version("3", "<"))
             | ternary("", ansible_facts.python.version.major | string) }}
        ansible_python_interpreter: >-
          /usr/bin/python{{ packages_python_bin_suffix }}
  tags:
    - role::packages
    - role::packages::python
