---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos6-${INSTANCE_UUID:-1}"
    image: centos:6
    groups:
      - molecule_hosts
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    groups:
      - molecule_hosts
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  inventory:
    hosts:
      molecule_hosts:
        vars:
          package_name: "httpd"
          packages_debug: yes
          packages_load_from_hostvars: yes
          packages_os:
            centos:
              all:
                telnet: present
              6:
                httpd: present
              7:
                - name: "{{ package_name }}"
                  state: present
                - tomcat: present
            fedora:
              29:
                httpd: present
                tomcat: present
              30:
                httpd: present
                tomcat: present
                "@Development Tools": present
          packages_python:
            centos:
              6:
                - "pexpect>=3.3": present
                - "gitlab": present
              7:
                "pexpect>=3.3": present
            fedora:
              29:
                - name: "pexpect>=3.3"
                  state: present
                  pip_extra_args: "--upgrade"
                  virtualenv: ~/.ansible_venv
                  virtualenv_site_packages: no
              30:
                "pexpect>=3.3": present
          packages_os_extra:
            all:
              all:
                lynx: present
          packages_python_extra:
            centos:
              7:
                lxml: present
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
