---

- name: Converge
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - role: amtega.packages
  tasks:
    - name: Get operating system packages facts
      package_facts:

    - name: Check operating system packages
      assert:
        that:
          - >-
            "httpd" in packages
          - >-
            "lynx" in packages
          - >-
            ansible_facts.distribution | lower != "centos"
            or (ansible_facts.distribution | lower == "centos"
                and "telnet" in packages)
          - >-
            ansible_facts.distribution_major_version is version("6", "==")
            or (ansible_facts.distribution_major_version is version("6", "!=")
                and "tomcat" in packages)
      vars:
        packages: "{{ ansible_facts.packages.keys() | list }}"

    - name: Get python packages facts
      command: "{{ packages_python_bin_dir }}pip list"
      changed_when: no
      register: pip_result

    - name: Get python packages facts in custon virtualal environment
      command: "~/.ansible_venv/bin/pip list"
      changed_when: no
      when: ansible_facts.distribution_major_version is version("29", "==")
      register: pip_venv_result

    - name: Check python packages
      assert:
        that:
          - pip_output is search("pexpect")

          - >-
            ansible_facts.distribution_major_version is version("7", "!=")
            or (ansible_facts.distribution_major_version is version("7", "==")
                and pip_output is search("lxml"))
      vars:
        pip_output: >-
          {{ (ansible_facts.distribution_major_version is version("29", "=="))
             | ternary(pip_venv_result.stdout | default(""),
                       pip_result.stdout) }}

    - name: Pause before replaying
      pause:
        seconds: 5

- name: Converge replay
  hosts: molecule_hosts
  gather_facts: no
  roles:
    - role: amtega.packages
