---

- name: Prepare EL 6/7 containers
  hosts:
    - molecule_hosts_centos_6
    - molecule_hosts_centos_7
  gather_facts: no
  roles:
    - amtega.python

- name: Prepare EL 8 containers
  hosts: molecule_hosts_centos_8
  gather_facts: no
  roles:
    - amtega.epel
  tasks:
    - name: Install dnf plugins core
      ansible.builtin.package:
        name: dnf-plugins-core
        state: present

    - name: Enable powertools repository
      ansible.builtin.command: dnf config-manager --set-enabled powertools
      when: yes
